name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install --save-dev typescript


      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      # Add deployment steps here if needed
